<a href="https://colab.research.google.com/github/AliK1977/DS_Assignments/blob/main/Stats_Assign_(Central_Tendency%26_Dispersion).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [ ]:
import numpy as np
import scipy 
import pandas as pd


 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
samples =np.random.normal(100,15,1000)
samples


array([ 88.58425802,  89.37523361,  84.92658642, 103.88611519,
        93.20903979,  92.01775333,  93.57961686,  90.50962781,
        56.66207611,  98.71615571,  66.7282125 , 107.2478953 ,
       103.77644647,  93.56855666,  93.54901885, 119.80173142,
        94.61310429, 103.75917931, 113.87630311,  89.62383053,
        75.08998306,  99.65054935,  92.09678645,  95.55847944,
        85.98815596,  95.0394874 ,  86.14869957, 116.67512178,
        97.16876691,  91.26785233, 100.4663498 ,  80.18158049,
        87.42487071, 124.13572365,  73.70634082,  95.60068055,
       102.4805214 , 109.58506886, 108.95183035,  89.15559745,
        64.88318482,  94.41391983,  86.93434298,  67.75451962,
       100.25791187, 100.99087188, 120.83321995,  86.82451949,
        84.00729993,  98.46125009,  83.28526826, 110.31877891,
       101.2872234 ,  78.5601681 ,  85.78260485,  83.82641179,
       120.94313295, 107.41528012,  88.01329158, 101.30140281,
       126.17719194,  76.69802799, 121.35246469, 115.85

Compute the **mean**, **median**, and **mode**

In [ ]:
from numpy.lib.function_base import median
import numpy as np
from scipy import stats

mean_samples = np.mean(samples)
print("mean:", mean_samples)

median_samples = np.median(samples)
print("median:", median_samples)

mode_samples= stats.mode(samples)
print("mode:",mode_samples)

mean: 99.51783106104692
median: 99.66960919060952
mode: ModeResult(mode=array([56.66207611]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
print("Min: ", (np.min(samples)))

print("Max: ", (np.max(samples)))

print("Q1:", (np.percentile(samples, 25)))

print("Q2:", (np.percentile(samples, 50)))  

print("Q3:", (np.percentile(samples, 75)))

print("IQR:", (stats.iqr(samples)))

Min:  56.66207610881703
Max:  153.6976566488126
Q1: 87.97914004418601
Q2: 99.66960919060952
Q3: 110.03470115626004
IQR: 22.05556111207403


Compute the **variance** and **standard deviation**

In [ ]:
print("Variance: ", (np.var(samples)))

print("Std: ", (np.std(samples)))

Variance:  243.58763748562689
Std:  15.607294367878978


Compute the **skewness** and **kurtosis**

You can use [`scipy.stats.skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html) and [`scipy.stats.kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)

In [ ]:
from scipy.stats import kurtosis, skew
from scipy import stats
scipy.stats. skew(samples)


0.07055509743762874

In [ ]:
scipy.stats.kurtosis(samples)

-0.3258186173303086

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
y

array([ 2,  1,  4,  5,  8, 12, 18, 25, 96, 48])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r = np.corrcoef(x, y)
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [ ]:
x

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [ ]:
y

0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r =scipy.stats.pearsonr(x, y)  # Pearson's r correlation.
r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho =scipy.stats.spearmanr(x, y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
df = sns.load_dataset("tips")

In [ ]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [49]:
df.corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000